spring:
  datasource:
    url: jdbc:mysql://localhost:3307/raota_test
    username: raota_user
    password: testpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # 또는 none
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  flyway:
    enabled: false

server:
  port: 8080